import test from 'node:test';
import assert from 'node:assert/strict';
import {buildPlan,extractActions} from '../src/index.js';
test('extracts owner channel and risk',()=>{const a=extractActions('ACTION: @sam email customer recap due 2026-07-01',[])[0];assert.equal(a.owner,'sam');assert.equal(a.channel,'email');assert.equal(a.risk,'high');});
test('requires approval for destructive and credential-related actions',()=>{for(const text of ['ACTION: @sam delete the production database','ACTION: @sam rotate leaked credentials']){const a=extractActions(text,[])[0];assert.equal(a.risk,'high');assert.equal(a.approvalRequired,true);}});
test('keeps clearly benign owned actions approval-free',()=>{const a=extractActions('ACTION: @sam draft the weekly agenda',[])[0];assert.equal(a.risk,'low');assert.equal(a.approvalRequired,false);});
test('matches attendee names case-insensitively at punctuation boundaries',()=>{for(const text of ['ACTION: SAM, draft the agenda','ACTION: Follow up with (sam).']){const a=extractActions(text,[{name:'Sam'}])[0];assert.equal(a.owner,'Sam');assert.equal(a.approvalRequired,false);}});
test('does not infer an attendee owner from a name embedded in another word',()=>{const plan=buildPlan({notes:'ACTION: Finish planning review',attendees:[{name:'Ann'}]});assert.equal(plan.actions[0].owner,null);assert.equal(plan.actions[0].approvalRequired,true);assert.deepEqual(plan.issues,[{id:'action-1',severity:'warning',message:'Missing owner'}]);});
test('strict mode rejects attendee names embedded in another word',()=>{assert.throws(()=>buildPlan({notes:'ACTION: Finish planning review',attendees:[{name:'Ann'}],strict:true}),/Missing owner/);});
test('strict mode fails missing owner',()=>{assert.throws(()=>buildPlan({notes:'TODO: Send recap email',strict:true}),/Missing owner/);});
test('buildPlan is deterministic without wall-clock provenance',()=>{const input={notes:'ACTION: @sam draft the agenda',attendees:[]};assert.deepEqual(buildPlan(input),buildPlan(input));assert.equal(buildPlan(input).generatedAt,null);});
test('buildPlan preserves an explicit generation timestamp',()=>{const generatedAt='2026-08-11T02:08:00.000Z';assert.equal(buildPlan({notes:'',generatedAt}).generatedAt,generatedAt);});
test('buildPlan rejects invalid generation timestamps',()=>{assert.throws(()=>buildPlan({notes:'',generatedAt:'today'}),/expected an ISO-8601 timestamp/);});
test('buildPlan rejects timestamp values outside the documented ISO profile',()=>{for(const generatedAt of ['2026','2026-08-11','Mon, 11 Aug 2026 02:08:00 GMT','2026-08-11T02:08:00']) assert.throws(()=>buildPlan({notes:'',generatedAt}),/expected an ISO-8601 timestamp/);});
test('extractActions ignores calendar-invalid due hints',()=>{for(const value of ['2026-02-29','2026-13-01']) assert.equal(extractActions(`ACTION: @sam prepare agenda due ${value}`)[0].due,null);});
test('extractActions preserves calendar-valid due hints',()=>{for(const value of ['2024-02-29','2026-12-31']) assert.equal(extractActions(`ACTION: @sam prepare agenda due ${value}`)[0].due,value);});
test('extractActions accepts documented weekday due hints case-insensitively',()=>{for(const weekday of ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday']){const value=`next ${weekday}`;assert.equal(extractActions(`ACTION: @sam prepare agenda due ${value}`)[0].due,value);}});
test('extractActions ignores unsupported relative due tokens',()=>{for(const value of ['next banana','next weekday','next someday']) assert.equal(extractActions(`ACTION: @sam prepare agenda due ${value}`)[0].due,null);});
