import fs from 'node:fs';
import path from 'node:path';
export function parseAttendees(file){return file?(JSON.parse(fs.readFileSync(file,'utf8')).attendees||[]):[];}
function owner(text,people){const m=text.match(/@([a-z0-9._-]+)/i);if(m) return m[1];const hit=people.find((p)=>text.toLowerCase().includes((p.name||'').toLowerCase()));return hit?hit.name:null;}
function due(text){const m=text.match(/due[: ]+([0-9]{4}-[0-9]{2}-[0-9]{2}|next [a-z]+)/i);return m?m[1]:null;}
function channel(text){const s=text.toLowerCase();return s.includes('email')?'email':s.includes('crm')?'crm':s.includes('calendar')?'calendar':'project-management';}
function risk(text){return /\b(?:contract|invoice|customer|external|deadline|delete|destroy|drop|erase|purge|remove|truncate|wipe|credentials?|passwords?|secrets?|api[ -]?keys?|access[ -]?tokens?|private[ -]?keys?)\b/i.test(text)?'high':(/email|publish|send/i.test(text)?'medium':'low');}
export function extractActions(markdown,attendees=[]){return markdown.split(/\r?\n/).map((line,i)=>({line,index:i+1})).filter(({line})=>/^\s*(- \[[ x]\]\s*)?(TODO|ACTION)[: -]/i.test(line)).map(({line,index},n)=>{const text=line.replace(/^\s*(- \[[ x]\]\s*)?(TODO|ACTION)[: -]\s*/i,'').trim();const r=risk(text);const o=owner(text,attendees);return {id:'action-'+(n+1),text,owner:o,due:due(text),channel:channel(text),risk:r,evidence:{line:index,source:line.trim()},approvalRequired:r!=='low'||!o};});}
export function validatePlan(actions,strict=false){const issues=[];for(const a of actions){if(!a.owner) issues.push({id:a.id,severity:strict?'error':'warning',message:'Missing owner'});if(!a.evidence||!a.evidence.line) issues.push({id:a.id,severity:'error',message:'Missing evidence line'});}if(strict&&issues.some((i)=>i.severity==='error')) throw new Error(issues.map((i)=>i.id+': '+i.message).join('; '));return issues;}
export function buildPlan({notes,attendees=[],strict=false}){const actions=extractActions(notes,attendees);return {generatedAt:new Date().toISOString(),actions,issues:validatePlan(actions,strict)};}
export function renderBrief(plan){const lines=['# Meeting Action Review','','Actions: '+plan.actions.length,'','## Proposed Actions'];for(const a of plan.actions) lines.push('- ['+a.risk+'] '+a.id+': '+a.text+' (owner: '+(a.owner||'needs-review')+', channel: '+a.channel+')');lines.push('','## Issues');if(!plan.issues.length) lines.push('- none');for(const i of plan.issues) lines.push('- '+i.severity+': '+i.id+' '+i.message);return lines.join('\n')+'\n';}
export function writePlan(plan,outDir){fs.mkdirSync(outDir,{recursive:true});fs.writeFileSync(path.join(outDir,'action-plan.json'),JSON.stringify(plan,null,2)+'\n');fs.writeFileSync(path.join(outDir,'review-brief.md'),renderBrief(plan));}
